spring.application.name=telemetry-service

server.port=8082

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/vehicle_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

alert.service.url=${ALERT_SERVICE_URL:http://localhost:8083}
vehicle.service.url=${VEHICLE_SERVICE_URL:http://localhost:8081}